CLOUDERA BUILD. Pull Snappy source, build it and wire it to Hadoop build

diff --git a/cloudera/do-release-build b/cloudera/do-release-build
--- a/cloudera/do-release-build
+++ b/cloudera/do-release-build
@@ -3,6 +3,9 @@
 #
 # Performs a release build
 
+#
+# Setup
+#
 set -e
 
 if [ $(uname -s) = "SunOS" ]; then
@@ -26,6 +29,63 @@ JAVA64_HOME=${JAVA64_HOME:-$JAVA_HOME}
 BIN_DIR=$(readlink -f $(dirname $0))
 RELEASE_DIR=$BIN_DIR/..
 
+failIfNotOK() {
+  if [ $? != 0 ]; then
+    echo "Failed!"
+    exit $?
+  fi
+}
+
+# Clean build directory
+#
+BUILDDIR=${RELEASE_DIR}/build
+rm -rf ${BUILDDIR}
+failIfNotOK
+mkdir ${BUILDDIR}
+failIfNotOK
+
+#
+# Building Snappy
+#
+
+echo "Downloading Snappy"
+
+SNAPPY_VERSION=1.0.3
+
+# Get Snappy source
+#
+${RELEASE_DIR}/cloudera/getsnappysource.sh ${SNAPPY_VERSION} ${RELEASE_DIR}/cloudera ${BUILDDIR}
+failIfNotOK
+
+echo "Building Snappy"
+
+SNAPPY_DIR=${BUILDDIR}/snappy-${SNAPPY_VERSION}
+cd ${SNAPPY_DIR}
+failIfNotOK
+
+./configure
+failIfNotOK
+
+# Disable rpath
+# TODO: find the correct way of disabling RPATH when running configure
+#
+sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=""|g' libtool
+sed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool
+
+SNAPPY_BUILDDIR=${SNAPPY_DIR}/build
+mkdir ${SNAPPY_BUILDDIR}
+
+LIBTOOL_VAR="LIBTOOL=libtool"
+if [ -f "/etc/SuSE-release" ]; then
+  LIBTOOL_VAR=""
+fi
+
+make install CXXFLAGS="-O2 -DNDEBUG" DESTDIR=${SNAPPY_BUILDDIR} ${LIBTOOL_VAR}
+failIfNotOK
+
+#
+# Building Hadoop
+#
 cd $RELEASE_DIR
 
 if [ -z "$SKIP_EXTRA_NATIVE" ]; then
@@ -41,7 +101,7 @@ JAVA_HOME=$JAVA32_HOME \
   -Dforrest.home=$FORREST_HOME \
   -Dhadoop.conf.dir=/etc/hadoop-0.20/conf \
   -propertyfile cloudera/build.properties \
-  clean task-controller package-native
+  task-controller package-native
 
 JAVA_HOME=$JAVA64_HOME
 fi
@@ -67,6 +127,8 @@ ant \
   -Dforrest.home=$FORREST_HOME \
   -Dhadoop.conf.dir=/etc/hadoop-0.20/conf \
   -propertyfile cloudera/build.properties \
+  -Dsnappy.prefix=${SNAPPY_BUILDDIR}/usr/local \
+  -Dbundle.snappy=true \
   compile-core-native compile-c++ compile-c++-examples task-controller tar
 
 if [ -z "$SKIP_MVN_EXPLICIT" ]; then
